more stuff

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -6,40 +6,25 @@ if [ "$#" -ne 1 ]; then
 fi
 
 lambda=$1
-echo "Packaging and deploying current directory to lambda function $lambda";
 
-npm install
-if [ $? -eq 0 ]; then
-  echo "done";
-else 
-  echo "npm install failed";
-  exit 1;
-fi
-
-echo "Checking that aws-cli is installed"
-which aws
-if [ $? -eq 0 ]; then
-  echo "aws-cli is installed, continuing..."
-else
+which aws &> /dev/null
+if [ ! $? -eq 0 ]; then
   echo "You need aws-cli to deploy this lambda. Google 'aws-cli install'"
   exit 1
 fi
 
-echo "removing old zip"
 rm archive.zip;
 
-echo "creating a new zip file"
-zip archive.zip *  -r -x .git/\* \*.sh tests/\* node_modules/aws-sdk/\* \*.zip
+echo "Creating zip file"
+zip archive.zip *  -r -x .git/\* \*.sh tests/\* node_modules/aws-sdk/\* \*.zip &> /dev/null
 
-echo "Uploading $lambda to $region";
+echo "Deploying to Lambda function $lambda..."
 
-aws lambda update-function-code --function-name $lambda --zip-file fileb://archive.zip --publish
+aws lambda update-function-code --function-name $lambda --zip-file fileb://archive.zip --publish &> /dev/null
 
 if [ $? -eq 0 ]; then
-  echo "!! Upload successful !!"
+  echo "Deployment succeeded"
 else 
-  echo "Upload failed"
-  echo "If the error was a 400, check that there are no slashes in your lambda name"
-  echo "Lambda name = $lambda"
+  echo "Deployment failed"
   exit 1;
 fi
